apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cluster-values.yaml
  - prometheus-rbac.yaml
  - servicemonitors.yaml
  - dashboards.yaml
  - grafana-httproute.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_BASE
    targets:
      - select:
          kind: HTTPRoute
          name: grafana
        fieldPaths:
          - spec.hostnames.0
        options:
          create: true
