apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cluster-values.yaml
  - envoy-proxy-kind.yaml
  - gatewayclass.yaml
  - gateway-https.yaml
  - https-redirect.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_WILDCARD
    targets:
      - select:
          kind: Gateway
          name: local
        fieldPaths:
          - spec.listeners.[name=https].hostname
