apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cluster-values.yaml
  - cloudflare-issuer.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_DOMAIN
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt-cloudflare
        fieldPaths:
          - spec.acme.solvers.[dns01].selector.dnsZones.0
      - select:
          kind: Certificate
          name: dev-tls
        fieldPaths:
          - spec.dnsNames.1
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_WILDCARD
    targets:
      - select:
          kind: Certificate
          name: dev-tls
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_BASE
    targets:
      - select:
          kind: Certificate
          name: dev-tls
        fieldPaths:
          - spec.dnsNames.1
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_EMAIL
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt-cloudflare
        fieldPaths:
          - spec.acme.email
