apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-values.yaml
  - httproute.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-values
      fieldPath: data.ACME_BASE
    targets:
      - select:
          kind: HTTPRoute
          name: hubble-ui
        fieldPaths:
          - spec.hostnames.1
        options:
          create: true
